[book]
authors = ["upsetgrass"]
language = "en"
multilingual = false
src = "docs"
title = "github_docs_example"

[output.html]
git-repository-url = "https://github/upsetgrass/github-docs/"
mathjax-support = true

[output.pdf]
optional = true
